#!/bin/bash
DIR=/var/app/mobiliteitserver
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
NODE_PATH=/var/app/mobiliteitserver/node_modules
NODE=/usr/bin/node

test -x $NODE || exit 0

function start_app {
  NODE_ENV=production nohup "$NODE" "$DIR/Server.js" 1>>"$DIR/logs/Server.log" 2>&1 &
  echo $! > "$DIR/pids/mobiliteitserver.pid"
}

function stop_app {
  kill `cat $DIR/pids/mobiliteitserver.pid`
}

case $1 in
   start)
      start_app ;;
    stop)
      stop_app ;;
    restart)
      stop_app
      start_app
      ;;
    *)
      echo "usage: mobiliteitserver {start|stop}" ;;
esac
exit 0